name: myapp
description: "Gogama Store - Your one-stop shop for everything."
publish_to: 'none'

version: 1.1.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # optional

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  go_router: ^16.2.2
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  intl: ^0.19.0
  badges: ^3.1.2
  rxdart: ^0.28.0
  cached_network_image: ^3.4.0
  image_picker: ^1.2.0
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
